databases:
  - name: data-viz-db
    plan: free
    databaseName: data_viz
    user: data_viz

services:
  - type: web
    name: data-viz
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: data-viz-db
          property: connectionString