"""add saved_item table

Revision ID: eacc29a176b9
Revises: d15a28268b4e
Create Date: 2026-08-01 15:04:57.376970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacc29a176b9'
down_revision = 'd15a28268b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'source_url', name='uq_saved_item_per_user')
    )
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_item_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_item_user_id'))

    op.drop_table('saved_item')
    # ### end Alembic commands ###
