"""add uv_session and uv_reading tables

Revision ID: f84dffe975da
Revises: 2885acea93ab
Create Date: 2026-08-22 16:48:45.098085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84dffe975da'
down_revision = '2885acea93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uv_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uv_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uv_session_user_id'), ['user_id'], unique=False)

    op.create_table('uv_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['uv_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uv_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uv_reading_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uv_reading_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uv_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uv_reading_session_id'))
        batch_op.drop_index(batch_op.f('ix_uv_reading_recorded_at'))

    op.drop_table('uv_reading')
    with op.batch_alter_table('uv_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uv_session_user_id'))

    op.drop_table('uv_session')
    # ### end Alembic commands ###
